using System.Text;
using ArchDiagram.Graph;

namespace ArchDiagram.Site;

/// <summary>Writes ARCHITECTURE.md next to the site — a self-contained markdown
/// summary with embedded Mermaid blocks that renders natively on GitHub/GitLab,
/// so the analysis can be committed straight into the documented repo.</summary>
public static class MarkdownExporter
{
    public static void Write(ProjectModel model, string path, int maxNodes, string generatedOn) =>
        Write(SiteContext.Build(model), path, maxNodes, generatedOn);

    /// <summary>Reuses the scorecard, metrics and importance ranking already computed in
    /// <paramref name="ctx"/> instead of recomputing them (each was previously built a
    /// second time here, duplicating the HTML page's work).</summary>
    public static void Write(SiteContext ctx, string path, int maxNodes, string generatedOn)
    {
        var model = ctx.Model;
        var sb = new StringBuilder();
        // First-party LOC (excludes tests and vendored bundles) so the figure matches the site.
        var totalLoc = Analysis.CodebaseStats.FirstPartyLoc(model);

        sb.AppendLine($"# {model.RootName} — Architecture");
        sb.AppendLine();
        sb.AppendLine($"> Generated by ArchDiagram on {generatedOn} from a static scan of `{model.SourcePath}`.");
        sb.AppendLine($"> Analysis is heuristic (no compilation); see the HTML site for interactive diagrams.");
        sb.AppendLine();

        AppendSummary(sb, model);
        AppendAtAGlance(sb, model, totalLoc);
        AppendScorecard(sb, ctx.Scorecard);
        if (model.LanguageLoc.Count > 0) { AppendLanguages(sb, model, totalLoc); }
        AppendArchitectureDiagram(sb, model, maxNodes);
        if (model.Projects.Count > 0) { AppendProjects(sb, model); }
        AppendKeyFiles(sb, ctx);
        if (ctx.Metrics.Modules.Count >= 2) { AppendArchitectureMetrics(sb, ctx.Metrics); }
        AppendOpenMarkers(sb, model);

        File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
    }

    private static void AppendSummary(StringBuilder sb, ProjectModel model)
    {
        sb.AppendLine("## Summary");
        sb.AppendLine();
        if (model.Description.Length > 0)
        {
            sb.AppendLine(model.Description);
            sb.AppendLine();
        }
        sb.AppendLine(Analysis.NarrativeBuilder.ProjectSummary(model));
        sb.AppendLine();
    }

    private static void AppendAtAGlance(StringBuilder sb, ProjectModel model, int totalLoc)
    {
        sb.AppendLine("## At a glance");
        sb.AppendLine();
        sb.AppendLine("| Metric | Value |");
        sb.AppendLine("|---|---|");
        sb.AppendLine($"| Files | {model.Files.Count:N0} |");
        sb.AppendLine($"| Lines of code | {totalLoc:N0} |");
        sb.AppendLine($"| Projects (.csproj) | {model.Projects.Count:N0} |");
        sb.AppendLine($"| Types | {model.Files.Sum(f => f.Types.Count):N0} |");
        sb.AppendLine($"| File-to-file links | {model.FileDependencies.Count(d => d.ToSlug.Length > 0):N0} |");
        sb.AppendLine($"| Databases | {model.Databases.Count:N0} |");
        sb.AppendLine();
    }

    private static void AppendLanguages(StringBuilder sb, ProjectModel model, int totalLoc)
    {
        sb.AppendLine("## Languages");
        sb.AppendLine();
        sb.AppendLine("| Language | LOC | Share |");
        sb.AppendLine("|---|---|---|");
        foreach (var (lang, loc) in model.LanguageLoc.OrderByDescending(kv => kv.Value))
        {
            sb.AppendLine($"| {lang} | {loc:N0} | {(totalLoc > 0 ? 100.0 * loc / totalLoc : 0):F1}% |");
        }
        sb.AppendLine();
    }

    private static void AppendArchitectureDiagram(StringBuilder sb, ProjectModel model, int maxNodes)
    {
        sb.AppendLine("## Architecture diagram");
        sb.AppendLine();
        var diagram = model.Projects.Count > 0
            ? ArchitectureDiagrams.BuildProjectDiagram(model, maxNodes)
            : ArchitectureDiagrams.BuildFolderOverview(model, maxNodes);
        sb.AppendLine("```mermaid");
        sb.Append(diagram.Mermaid);
        sb.AppendLine("```");
        sb.AppendLine();
    }

    private static void AppendProjects(StringBuilder sb, ProjectModel model)
    {
        sb.AppendLine("## Projects");
        sb.AppendLine();
        sb.AppendLine("| Project | Framework | References | Packages |");
        sb.AppendLine("|---|---|---|---|");
        foreach (var p in model.Projects.OrderBy(p => p.Name, StringComparer.OrdinalIgnoreCase))
        {
            var refs = p.ProjectReferenceNames.Count > 0 ? string.Join(", ", p.ProjectReferenceNames) : "—";
            var pkgs = p.PackageReferences.Count > 0
                ? string.Join(", ", p.PackageReferences.Take(8)) + (p.PackageReferences.Count > 8 ? ", …" : "")
                : "—";
            sb.AppendLine($"| {p.Name} | {(p.TargetFramework.Length > 0 ? p.TargetFramework : "?")} | {refs} | {pkgs} |");
        }
        sb.AppendLine();
    }

    // Key files: ranked by overall importance (fan-in, calls, entry points, size).
    // ctx.Ranked is cached at take=20; slicing to 10 here reproduces Rank(model, 10)
    // exactly since ordering doesn't depend on `take`.
    private static void AppendKeyFiles(StringBuilder sb, SiteContext ctx)
    {
        var key = ctx.Ranked.Take(10).ToList();
        if (key.Count == 0) { return; }

        sb.AppendLine("## Key files (start here)");
        sb.AppendLine();
        sb.AppendLine("| # | File | Why it matters | Imported by | Purpose |");
        sb.AppendLine("|---|---|---|---|---|");
        var rank = 0;
        foreach (var s in key)
        {
            rank++;
            sb.AppendLine($"| {rank} | `{s.File.RelPath}` | {MdEscape(s.Reason)} | {s.FanIn} files | {MdEscape(s.File.Purpose)} |");
        }
        sb.AppendLine();
    }

    private static void AppendArchitectureMetrics(StringBuilder sb, Analysis.ArchitectureMetrics.Result metrics)
    {
        sb.AppendLine("## Architecture metrics");
        sb.AppendLine();
        sb.AppendLine($"Propagation cost: **{metrics.PropagationCost:P0}** · dependency cycles: **{metrics.Cycles.Count}** (module level, heuristic).");
        sb.AppendLine();
        sb.AppendLine("Highest distance from the main sequence (D = |A + I − 1|):");
        sb.AppendLine();
        sb.AppendLine("| Module | Instability | Abstractness | Distance |");
        sb.AppendLine("|---|---|---|---|");
        foreach (var m in metrics.Modules.Take(5))
        {
            sb.AppendLine($"| `{MdEscape(m.Key)}` | {m.Instability:F2} | {m.Abstractness:F2} | {m.Distance:F2} |");
        }
        sb.AppendLine();
    }

    private static void AppendOpenMarkers(StringBuilder sb, ProjectModel model)
    {
        var todoCount = model.Files.Sum(f => f.Todos.Count);
        if (todoCount == 0) { return; }

        sb.AppendLine($"## Open markers");
        sb.AppendLine();
        sb.AppendLine($"{todoCount} TODO/FIXME/HACK markers found — see `hotspots.html` in the generated site for the full list.");
        sb.AppendLine();
    }

    private static void AppendScorecard(StringBuilder sb, Analysis.ScorecardBuilder.Card card)
    {
        var overall = card.Overall switch
        {
            Analysis.ScorecardBuilder.Status.Ok => "PASS",
            Analysis.ScorecardBuilder.Status.Watch => "WATCH",
            Analysis.ScorecardBuilder.Status.Fail => "AT RISK",
            _ => "—",
        };
        sb.AppendLine($"## Architecture scorecard — {overall}");
        sb.AppendLine();
        sb.AppendLine("| Signal | Value | Grade | Meaning | What to do |");
        sb.AppendLine("|---|---|---|---|---|");
        foreach (var r in card.Rows)
        {
            var grade = r.Status switch
            {
                Analysis.ScorecardBuilder.Status.Ok => "pass",
                Analysis.ScorecardBuilder.Status.Watch => "watch",
                Analysis.ScorecardBuilder.Status.Fail => "fail",
                _ => "n/a",
            };
            var action = r.Action.Length == 0 ? "—" : r.Action;
            sb.AppendLine($"| {MdEscape(r.Metric)} | {MdEscape(r.Value)} | {grade} | {MdEscape(r.Note)} | {MdEscape(action)} |");
        }
        sb.AppendLine();
    }

    private static string MdEscape(string s) => s.Replace("|", "\\|").Replace("\n", " ");
}
