using System.Text;
using ArchDiagram.Graph;
using ArchDiagram.Site.Pages;

namespace ArchDiagram.Site;

/// <summary>Writes ARCHITECTURE.md next to the site — a self-contained markdown
/// summary with embedded Mermaid blocks that renders natively on GitHub/GitLab,
/// so the analysis can be committed straight into the documented repo.</summary>
public static class MarkdownExporter
{
    public static void Write(ProjectModel model, string path, int maxNodes, string generatedOn)
    {
        var sb = new StringBuilder();
        var totalLoc = model.LanguageLoc.Values.Sum();

        sb.AppendLine($"# {model.RootName} — Architecture");
        sb.AppendLine();
        sb.AppendLine($"> Generated by ArchDiagram on {generatedOn} from a static scan of `{model.SourcePath}`.");
        sb.AppendLine($"> Analysis is heuristic (no compilation); see the HTML site for interactive diagrams.");
        sb.AppendLine();

        sb.AppendLine("## At a glance");
        sb.AppendLine();
        sb.AppendLine("| Metric | Value |");
        sb.AppendLine("|---|---|");
        sb.AppendLine($"| Files | {model.Files.Count:N0} |");
        sb.AppendLine($"| Lines of code | {totalLoc:N0} |");
        sb.AppendLine($"| Projects (.csproj) | {model.Projects.Count:N0} |");
        sb.AppendLine($"| Types | {model.Files.Sum(f => f.Types.Count):N0} |");
        sb.AppendLine($"| File-to-file links | {model.FileDependencies.Count(d => d.ToSlug.Length > 0):N0} |");
        sb.AppendLine($"| Databases | {model.Databases.Count:N0} |");
        sb.AppendLine();

        if (model.LanguageLoc.Count > 0)
        {
            sb.AppendLine("## Languages");
            sb.AppendLine();
            sb.AppendLine("| Language | LOC | Share |");
            sb.AppendLine("|---|---|---|");
            foreach (var (lang, loc) in model.LanguageLoc.OrderByDescending(kv => kv.Value))
            {
                sb.AppendLine($"| {lang} | {loc:N0} | {(totalLoc > 0 ? 100.0 * loc / totalLoc : 0):F1}% |");
            }
            sb.AppendLine();
        }

        sb.AppendLine("## Architecture diagram");
        sb.AppendLine();
        var diagram = model.Projects.Count > 0
            ? IndexPage.BuildProjectDiagram(model, maxNodes)
            : DependenciesPage.BuildFolderOverview(model, maxNodes);
        sb.AppendLine("```mermaid");
        sb.Append(diagram.Mermaid);
        sb.AppendLine("```");
        sb.AppendLine();

        if (model.Projects.Count > 0)
        {
            sb.AppendLine("## Projects");
            sb.AppendLine();
            sb.AppendLine("| Project | Framework | References | Packages |");
            sb.AppendLine("|---|---|---|---|");
            foreach (var p in model.Projects.OrderBy(p => p.Name, StringComparer.OrdinalIgnoreCase))
            {
                var refs = p.ProjectReferenceNames.Count > 0 ? string.Join(", ", p.ProjectReferenceNames) : "—";
                var pkgs = p.PackageReferences.Count > 0
                    ? string.Join(", ", p.PackageReferences.Take(8)) + (p.PackageReferences.Count > 8 ? ", …" : "")
                    : "—";
                sb.AppendLine($"| {p.Name} | {(p.TargetFramework.Length > 0 ? p.TargetFramework : "?")} | {refs} | {pkgs} |");
            }
            sb.AppendLine();
        }

        // Key files: highest fan-in with purposes.
        var fanIn = new Dictionary<string, int>(StringComparer.Ordinal);
        foreach (var e in model.FileDependencies.Where(e => e.ToSlug.Length > 0))
        {
            fanIn[e.ToSlug] = fanIn.GetValueOrDefault(e.ToSlug) + 1;
        }
        var bySlug = model.Files.ToDictionary(f => f.Slug, StringComparer.Ordinal);
        var key = fanIn.OrderByDescending(kv => kv.Value).Take(10)
            .Select(kv => (File: bySlug.GetValueOrDefault(kv.Key), Count: kv.Value))
            .Where(x => x.File is not null).ToList();
        if (key.Count > 0)
        {
            sb.AppendLine("## Key files (most depended-on)");
            sb.AppendLine();
            sb.AppendLine("| File | Imported by | Purpose |");
            sb.AppendLine("|---|---|---|");
            foreach (var (f, count) in key)
            {
                sb.AppendLine($"| `{f!.RelPath}` | {count} files | {MdEscape(f.Purpose)} |");
            }
            sb.AppendLine();
        }

        var todoCount = model.Files.Sum(f => f.Todos.Count);
        if (todoCount > 0)
        {
            sb.AppendLine($"## Open markers");
            sb.AppendLine();
            sb.AppendLine($"{todoCount} TODO/FIXME/HACK markers found — see `hotspots.html` in the generated site for the full list.");
            sb.AppendLine();
        }

        File.WriteAllText(path, sb.ToString(), new UTF8Encoding(false));
    }

    private static string MdEscape(string s) => s.Replace("|", "\\|").Replace("\n", " ");
}
