using System.Text;
using ArchDiagram.Graph;
using ArchDiagram.Site.Pages;

namespace ArchDiagram.Site;

/// <summary>Exports the analysis for a wiki. Current output target: Confluence
/// Storage Format (XHTML with ac:/ri: macros) — this is NOT portable to other
/// wikis (MediaWiki, Notion, …); see plan Constraint 8. Pure render methods
/// return the storage-format body of a page (no html/head wrapper); Write is the
/// thin I/O shell. The bodies are exactly what Confluence's REST
/// POST /wiki/rest/api/content expects as body.storage.value, should anyone script
/// an upload later — but no publishing happens here (fully offline).</summary>
public static class WikiExporter
{
    public static void Write(ProjectModel model, string dir, int maxNodes, string generatedOn, bool includeComplexity) =>
        Write(SiteContext.Build(model), dir, maxNodes, generatedOn, includeComplexity);

    /// <summary>Reuses the fan-in/fan-out indexes already computed in <paramref name="ctx"/>
    /// for the hotspots page instead of rescanning model.FileDependencies a second time.</summary>
    public static void Write(SiteContext ctx, string dir, int maxNodes, string generatedOn, bool includeComplexity)
    {
        var model = ctx.Model;
        Directory.CreateDirectory(dir);
        var utf8 = new UTF8Encoding(false);
        File.WriteAllText(Path.Combine(dir, "overview.xhtml"),
            Document($"{model.RootName} — Architecture", RenderOverview(model, maxNodes, generatedOn)), utf8);
        File.WriteAllText(Path.Combine(dir, "hotspots.xhtml"),
            Document($"{model.RootName} — Hotspots", RenderHotspots(ctx, includeComplexity)), utf8);
        File.WriteAllText(Path.Combine(dir, "README.md"),
            RenderReadme(model, includeComplexity), utf8);
    }

    /// <summary>Storage-format body for the architecture overview page.</summary>
    public static string RenderOverview(ProjectModel model, int maxNodes, string generatedOn)
    {
        var totalLoc = model.LanguageLoc.Values.Sum();
        var sb = new StringBuilder();

        sb.Append(Toc());
        sb.Append(Panel("info", $"Generated by ArchDiagram on {E(generatedOn)} from a static scan of " +
                                 $"{Code(model.SourcePath)}. Analysis is heuristic (no compilation) — see the HTML " +
                                 "site for interactive diagrams."));

        sb.Append("<h2>At a glance</h2>");
        sb.Append("<table><tbody><tr><th>Metric</th><th>Value</th></tr>");
        Row(sb, "Files", model.Files.Count.ToString("N0"));
        Row(sb, "Lines of code", totalLoc.ToString("N0"));
        Row(sb, "Projects (.csproj)", model.Projects.Count.ToString("N0"));
        Row(sb, "Types", model.Files.Sum(f => f.Types.Count).ToString("N0"));
        Row(sb, "File-to-file links", model.FileDependencies.Count(d => d.ToSlug.Length > 0).ToString("N0"));
        Row(sb, "Databases", model.Databases.Count.ToString("N0"));
        sb.Append("</tbody></table>");

        if (model.LanguageLoc.Count > 0)
        {
            sb.Append("<h2>Languages</h2>");
            sb.Append("<table><tbody><tr><th>Language</th><th>LOC</th><th>Share</th></tr>");
            foreach (var (lang, loc) in model.LanguageLoc.OrderByDescending(kv => kv.Value))
            {
                var share = totalLoc > 0 ? 100.0 * loc / totalLoc : 0;
                sb.Append($"<tr><td>{E(lang)}</td><td>{loc:N0}</td><td>{share:F1}%</td></tr>");
            }
            sb.Append("</tbody></table>");
        }

        sb.Append("<h2>Architecture diagram</h2>");
        var diagram = model.Projects.Count > 0
            ? IndexPage.BuildProjectDiagram(model, maxNodes)
            : DependenciesPage.BuildFolderOverview(model, maxNodes);
        sb.Append(MermaidMacro(diagram.Mermaid));

        if (model.Projects.Count > 0)
        {
            sb.Append("<h2>Projects</h2>");
            sb.Append("<table><tbody><tr><th>Project</th><th>Framework</th><th>References</th><th>Packages</th></tr>");
            foreach (var p in model.Projects.OrderBy(p => p.Name, StringComparer.OrdinalIgnoreCase))
            {
                var refs = p.ProjectReferenceNames.Count > 0 ? string.Join(", ", p.ProjectReferenceNames) : "—";
                var pkgs = p.PackageReferences.Count > 0
                    ? string.Join(", ", p.PackageReferences.Take(8)) + (p.PackageReferences.Count > 8 ? ", …" : "")
                    : "—";
                sb.Append($"<tr><td>{E(p.Name)}</td><td>{E(p.TargetFramework.Length > 0 ? p.TargetFramework : "?")}</td>" +
                          $"<td>{E(refs)}</td><td>{E(pkgs)}</td></tr>");
            }
            sb.Append("</tbody></table>");
        }

        var key = KeyFiles(model);
        if (key.Count > 0)
        {
            sb.Append("<h2>Key files (most depended-on)</h2>");
            var t = new StringBuilder("<table><tbody><tr><th>File</th><th>Imported by</th><th>Purpose</th></tr>");
            foreach (var (f, count) in key)
            {
                t.Append($"<tr><td>{Code(f.RelPath)}</td><td>{count} files</td><td>{E(f.Purpose)}</td></tr>");
            }
            t.Append("</tbody></table>");
            sb.Append(Expand($"Show the {key.Count} most depended-on files", t.ToString()));
        }

        return sb.ToString();
    }

    /// <summary>Storage-format body for the hotspots/metrics page.</summary>
    public static string RenderHotspots(ProjectModel model, bool includeComplexity) =>
        RenderHotspots(SiteContext.Build(model), includeComplexity);

    /// <summary>Reuses the fan-in/fan-out indexes already computed in <paramref name="ctx"/>.</summary>
    public static string RenderHotspots(SiteContext ctx, bool includeComplexity)
    {
        var model = ctx.Model;
        var bySlug = ctx.BySlug;
        var fanIn = ctx.FanIn;
        var fanOut = ctx.FanOut;

        var sb = new StringBuilder();
        sb.Append("<h2>Most depended-on files (fan-in)</h2>");
        RankTable(sb, fanIn, bySlug, "Imported by");
        sb.Append("<h2>Most dependencies (fan-out)</h2>");
        RankTable(sb, fanOut, bySlug, "Imports");

        sb.Append("<h2>Largest files</h2>");
        sb.Append("<table><tbody><tr><th>File</th><th>Language</th><th>LOC</th></tr>");
        foreach (var f in model.Files.OrderByDescending(f => f.Loc).Take(20))
        {
            sb.Append($"<tr><td>{Code(f.RelPath)}</td><td>{E(f.Language)}</td><td>{f.Loc:N0}</td></tr>");
        }
        sb.Append("</tbody></table>");

        if (includeComplexity)
        {
            var methods = model.Files
                .SelectMany(f => f.Types.SelectMany(t => t.Methods.Select(m => (f.RelPath, t.Name, m))))
                .Where(x => x.m.Cyclomatic > 1 || x.m.Cognitive > 0)
                .OrderByDescending(x => x.m.Cognitive).ThenByDescending(x => x.m.Cyclomatic)
                .Take(25).ToList();
            if (methods.Count > 0)
            {
                sb.Append("<h2>Most complex methods</h2>");
                sb.Append("<p>Ranked by SonarSource cognitive complexity (control-flow tangle); cyclomatic " +
                          "complexity (independent paths) shown alongside. Only C# methods are scored.</p>");
                var t = new StringBuilder("<table><tbody><tr><th>Method</th><th>File</th><th>Type</th>" +
                          "<th>Cyclomatic</th><th>Cognitive</th><th>Level</th></tr>");
                foreach (var (relPath, typeName, m) in methods)
                {
                    t.Append($"<tr><td>{E(m.Name)}</td><td>{Code(relPath)}</td><td>{E(typeName)}</td>" +
                             $"<td>{m.Cyclomatic:N0}</td><td>{m.Cognitive:N0}</td><td>{SeverityLozenge(m.Cognitive)}</td></tr>");
                }
                t.Append("</tbody></table>");
                sb.Append(Expand($"Show the {methods.Count} most complex methods", t.ToString()));
            }
        }

        var todoCount = model.Files.Sum(f => f.Todos.Count);
        sb.Append($"<h2>Open markers</h2><p>{todoCount:N0} TODO/FIXME/HACK/BUG markers found in comments.</p>");
        return sb.ToString();
    }

    private static string RenderReadme(ProjectModel model, bool includeComplexity)
    {
        var complexityNote = includeComplexity
            ? "- `hotspots.xhtml` includes a **Most complex methods** table (cyclomatic + cognitive).\n"
            : "";
        return
$@"# ArchDiagram wiki export — {model.RootName}

**Current target: Confluence Storage Format** (XHTML with `ac:`/`ri:` macros). These
files are *not* portable to other wikis (MediaWiki, Notion, …).

## Files
- `overview.xhtml` — architecture overview: at-a-glance metrics, languages, the
  architecture diagram (Mermaid), projects, and key files.
- `hotspots.xhtml` — coupling (fan-in/fan-out), largest files, open markers.
{complexityNote}
Each `.xhtml` file is a complete, browser-viewable XHTML document that *wraps* a
Confluence storage-format body. Opening it in a browser renders the tables and
headings (the Mermaid macro shows only in Confluence). There is **no one-click
import** and no network step here — this is an offline artifact. Two manual routes:

1. **Paste route (most reliable):** open the `.xhtml` file in a browser, select and
   copy the rendered content, and paste it into a new Confluence page. Confluence
   converts pasted rich HTML. *You may need to re-select the language on the pasted
   Mermaid code block.*
2. **REST route (admins):** copy the markup **between the `STORAGE-BODY START` and
   `STORAGE-BODY END` comments** inside the file — that fragment is exactly what
   `POST /wiki/rest/api/content` expects as `body.storage.value`, if you want to
   script the upload yourself.

## In-Confluence formatting
The pages use native Confluence macros that render on import: a table-of-contents,
info panels, collapsible **expand** sections for the long tables, and coloured
**status lozenges** for complexity levels (Green→Low … Red→Very High). These show
as plain content (or nothing) in a raw browser preview but come alive in Confluence.

## Mermaid diagrams
Confluence has **no native Mermaid**. The diagram is emitted as a `code` macro
tagged `mermaid`, which renders if your space has a Mermaid app installed. If it
does not, the macro simply shows the raw Mermaid source in a monospaced block —
still readable and copyable. All tables render regardless.
";
    }

    // ---- Storage-format helpers ----

    private static void Row(StringBuilder sb, string metric, string value) =>
        sb.Append($"<tr><td>{E(metric)}</td><td>{E(value)}</td></tr>");

    private static void RankTable(StringBuilder sb, IReadOnlyDictionary<string, int> counts,
        IReadOnlyDictionary<string, FileNode> bySlug, string verb)
    {
        sb.Append($"<table><tbody><tr><th>File</th><th>{E(verb)}</th></tr>");
        foreach (var (slug, count) in counts.OrderByDescending(kv => kv.Value).Take(15))
        {
            var f = bySlug.GetValueOrDefault(slug);
            if (f is null) { continue; }
            sb.Append($"<tr><td>{Code(f.RelPath)}</td><td>{count:N0}</td></tr>");
        }
        sb.Append("</tbody></table>");
    }

    private static List<(FileNode File, int Count)> KeyFiles(ProjectModel model)
    {
        var fanIn = new Dictionary<string, int>(StringComparer.Ordinal);
        foreach (var e in model.FileDependencies.Where(e => e.ToSlug.Length > 0))
        {
            fanIn[e.ToSlug] = fanIn.GetValueOrDefault(e.ToSlug) + 1;
        }
        var bySlug = model.Files.ToDictionary(f => f.Slug, StringComparer.Ordinal);
        return fanIn.OrderByDescending(kv => kv.Value).Take(10)
            .Select(kv => (File: bySlug.GetValueOrDefault(kv.Key), Count: kv.Value))
            .Where(x => x.File is not null)
            .Select(x => (x.File!, x.Count))
            .ToList();
    }

    /// <summary>A Confluence code macro holding the Mermaid source. The CDATA split
    /// guards against a stray "]]>" inside the diagram text closing the section early.</summary>
    private static string MermaidMacro(string mermaid)
    {
        var safe = mermaid.Replace("]]>", "]]]]><![CDATA[>");
        return "<ac:structured-macro ac:name=\"code\">" +
               "<ac:parameter ac:name=\"language\">mermaid</ac:parameter>" +
               $"<ac:plain-text-body><![CDATA[{safe}]]></ac:plain-text-body>" +
               "</ac:structured-macro>";
    }

    /// <summary>Wraps a storage-format fragment in a complete, valid XHTML document so
    /// the file opens cleanly in a browser (tables/headings render for the copy-paste
    /// import route). The ac:/ri: namespaces are declared so it stays well-formed XML;
    /// a browser simply ignores the unknown-namespace macro elements (they render in
    /// Confluence). The storage body for the REST route is the content between the two
    /// STORAGE-BODY markers.</summary>
    private static string Document(string title, string storageBody) =>
        "<!DOCTYPE html>\n" +
        "<html xmlns=\"http://www.w3.org/1999/xhtml\" " +
        "xmlns:ac=\"http://www.atlassian.com/schema/confluence/4/ac/\" " +
        "xmlns:ri=\"http://www.atlassian.com/schema/confluence/4/ri/\" lang=\"en\">\n" +
        $"<head><meta charset=\"utf-8\"/><title>{E(title)}</title>\n{PreviewCss}</head>\n" +
        "<body>\n<!-- STORAGE-BODY START (paste this element's contents into Confluence storage format) -->\n" +
        storageBody +
        "\n<!-- STORAGE-BODY END -->\n</body>\n</html>\n";

    /// <summary>Inline CSS for the local browser preview only. Confluence strips it on
    /// import and applies its own theme; it exists purely so the .xhtml file looks like
    /// the site when opened from disk. Theme-aware (light/dark).</summary>
    private const string PreviewCss = """
<style>
  body { font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    max-width: 1040px; margin: 2rem auto; padding: 0 1.3rem; line-height: 1.55;
    color: #1d2733; background: #fff; }
  h1 { font-size: 1.7rem; } h1, h2, h3 { line-height: 1.25; }
  h2 { margin-top: 2.2rem; border-bottom: 1px solid #dde3ea; padding-bottom: .35rem; }
  a { color: #2f6fab; }
  table { border-collapse: collapse; width: 100%; margin: .7rem 0; font-size: .92rem; }
  th, td { border: 1px solid #dde3ea; padding: .45rem .65rem; text-align: left; vertical-align: top; }
  th { background: #f0f3f7; font-weight: 600; }
  tr:nth-child(even) td { background: #fafbfd; }
  code { font-family: "Cascadia Code", Consolas, monospace; font-size: .88em;
    background: #eef1f5; padding: .1em .35em; border-radius: 4px; }
  em { color: #5b6b7c; }
  @media (prefers-color-scheme: dark) {
    body { color: #dbe4ee; background: #0f141a; }
    h2 { border-color: #2b3543; } a { color: #6aa9e0; }
    th, td { border-color: #2b3543; } th { background: #151a21; }
    tr:nth-child(even) td { background: #12171e; }
    code { background: #151a21; } em { color: #8b9bad; }
  }
</style>
""";

    // ---- Confluence-native UX macros (render in Confluence; browsers show the
    // inner rich-text content but not the macro chrome) ----

    /// <summary>Table-of-contents macro placed at the top of each page.</summary>
    private static string Toc() => "<ac:structured-macro ac:name=\"toc\"/>";

    /// <summary>An info/note/warning panel wrapping a single paragraph of rich text.</summary>
    private static string Panel(string kind, string innerHtml) =>
        $"<ac:structured-macro ac:name=\"{kind}\"><ac:rich-text-body><p>{innerHtml}</p></ac:rich-text-body></ac:structured-macro>";

    /// <summary>A collapsible "expand" section. The inner content still renders in a
    /// plain browser preview (just not collapsed), so it is safe for both routes.</summary>
    private static string Expand(string title, string bodyHtml) =>
        "<ac:structured-macro ac:name=\"expand\">" +
        $"<ac:parameter ac:name=\"title\">{E(title)}</ac:parameter>" +
        $"<ac:rich-text-body>{bodyHtml}</ac:rich-text-body></ac:structured-macro>";

    /// <summary>Severity as a coloured Confluence status lozenge (Low→Green, Moderate→Blue,
    /// High→Yellow, Very High→Red).</summary>
    private static string SeverityLozenge(int score)
    {
        var (label, _) = Severity.Band(score);
        var colour = label switch
        {
            "Low" => "Green",
            "Moderate" => "Blue",
            "High" => "Yellow",
            _ => "Red",
        };
        return "<ac:structured-macro ac:name=\"status\">" +
               $"<ac:parameter ac:name=\"colour\">{colour}</ac:parameter>" +
               $"<ac:parameter ac:name=\"title\">{E(label)}</ac:parameter></ac:structured-macro>";
    }

    private static string E(string s) => Html.Encode(s);
    private static string Code(string s) => $"<code>{Html.Encode(s)}</code>";
}
