using System.Text;
using ArchDiagram.Analysis;
using ArchDiagram.Graph;

namespace ArchDiagram.Site.Pages;

/// <summary>A one-page, printable executive brief: what the system is, its size and stack, its
/// health grade, integration points, and the top things to fix — assembled from the same analyses
/// as the rest of the site so it never disagrees. The artifact to hand to a stakeholder or bring
/// to a review, or the first page a new architect reads.</summary>
public static class BriefPage
{
    public static string Body(ProjectModel model, string generatedOn)
    {
        var sb = new StringBuilder();
        sb.Append("<h1>System Brief <button class=\"btn\" onclick=\"window.print()\" type=\"button\" style=\"float:right;font-weight:400\">🖨 Print</button></h1>");
        sb.Append($"<p class=\"note\">{Html.Encode(model.RootName)} · generated by ArchDiagram on {Html.Encode(generatedOn)} · heuristic, syntax-only.</p>");

        // What it is.
        if (model.Description.Length > 0)
        {
            sb.Append($"<div class=\"panel\"><strong>About</strong> <span class=\"badge accent\">authored</span>"
                    + $"<p style=\"margin:.4rem 0 0\">{Html.Encode(model.Description)}</p></div>");
        }
        sb.Append($"<p class=\"lede\">{Html.Encode(NarrativeBuilder.ProjectSummary(model))}</p>");

        // Size at a glance.
        var loc = CodebaseStats.FirstPartyLoc(model);
        var typeCount = model.Files.Where(CodebaseStats.IsFirstParty).Sum(f => f.Types.Count);
        sb.Append("<div class=\"tiles\">");
        Tile(sb, model.Files.Count.ToString("N0"), "Files");
        Tile(sb, loc.ToString("N0"), "First-party LOC");
        Tile(sb, model.Projects.Count.ToString("N0"), "Projects");
        Tile(sb, typeCount.ToString("N0"), "Types");
        Tile(sb, model.Databases.Count.ToString("N0"), "Databases");
        sb.Append("</div>");

        // Health grade + failing signals.
        var card = ScorecardBuilder.Build(model);
        var (label, cls) = card.Overall switch
        {
            ScorecardBuilder.Status.Ok => ("PASS", "ok"),
            ScorecardBuilder.Status.Watch => ("WATCH", "warn"),
            ScorecardBuilder.Status.Fail => ("AT RISK", "danger"),
            _ => ("—", "border"),
        };
        var attention = card.Rows.Where(r => r.Status is ScorecardBuilder.Status.Watch or ScorecardBuilder.Status.Fail).ToList();
        sb.Append($"<h2>Health <span class=\"badge {(cls == "ok" ? "ok" : "warn")}\">{label}</span> "
                + "<a href=\"scorecard.html\" style=\"font-size:.8rem;font-weight:400\">scorecard →</a></h2>");
        sb.Append(attention.Count == 0
            ? "<p class=\"note\">All measured signals pass.</p>"
            : "<p class=\"note\">Needs attention: " + string.Join(", ",
                attention.Select(r => $"<strong>{Html.Encode(r.Metric)}</strong> ({Html.Encode(r.Value)})")) + ".</p>");

        // Stack + integration.
        var stack = TechStack.Detect(model);
        if (stack.Count > 0)
        {
            sb.Append("<h2>Stack</h2><div class=\"lang-legend\" style=\"gap:.4rem\">");
            foreach (var t in stack) { sb.Append($"<span class=\"badge accent\" title=\"{Html.Encode(t.Category)}\">{Html.Encode(t.Name)}</span>"); }
            sb.Append("</div>");
        }
        var integ = stack.Where(t => TechStack.IntegrationCategories.Contains(t.Category)).ToList();
        if (model.Databases.Count > 0 || integ.Count > 0)
        {
            sb.Append("<h2>Integration points</h2><p class=\"note\">"
                    + string.Join(" · ",
                        model.Databases.Select(d => "DB: " + Html.Encode(d.Label))
                        .Concat(integ.Select(t => Html.Encode(t.Name))))
                    + " <a href=\"packages.html\" style=\"font-size:.8rem\">details →</a></p>");
        }

        // Top actions.
        var backlog = RefactoringBacklog.Build(model);
        sb.Append($"<h2>Top actions <a href=\"refactor.html\" style=\"font-size:.8rem;font-weight:400\">full backlog ({backlog.Count}) →</a></h2>");
        if (backlog.Count == 0)
        {
            sb.Append("<p class=\"note\">No refactoring findings surfaced.</p>");
        }
        else
        {
            sb.Append("<ol style=\"margin:.3rem 0 0;padding-left:1.2rem\">");
            foreach (var i in backlog.Take(5))
            {
                sb.Append($"<li><strong>{Html.Encode(i.Title)}</strong> — {Html.Encode(i.Tip)}</li>");
            }
            sb.Append("</ol>");
        }

        // Where to read first.
        var start = ImportanceScorer.Rank(model, 5).Where(s => CodebaseStats.IsFirstParty(s.File)).ToList();
        if (start.Count > 0)
        {
            sb.Append("<h2>Start reading here</h2><p class=\"note\">"
                    + string.Join(" · ", start.Select(s => $"<a href=\"files/{s.File.Slug}.html\">{Html.Encode(s.File.RelPath.Split('/')[^1])}</a>"))
                    + "</p>");
        }
        return sb.ToString();
    }

    private static void Tile(StringBuilder sb, string num, string label) =>
        sb.Append($"<div class=\"tile\"><div class=\"num\">{num}</div><div class=\"lbl\">{Html.Encode(label)}</div></div>");
}
