using System.Text;
using ArchDiagram.Graph;

namespace ArchDiagram.Site.Pages;

/// <summary>Orientation page: what each section of the site shows, how to read the
/// diagrams (embedded legend), the limits of the static/heuristic analysis, keyboard
/// shortcuts, and a glossary. Mostly static copy, but page names/links are data-driven
/// so a renamed or removed page never leaves a dangling reference.</summary>
public static class GuidePage
{
    private static readonly (string Href, string Title, string What)[] PageGuide =
    [
        ("index.html", "Overview", "Size, language mix, the top-level architecture diagram, and any scan diagnostics."),
        ("structure.html", "Structure", "The full folder/file tree — expand and filter it, then click a file for its detail page."),
        ("dependencies.html", "Dependencies", "Which files and folders import each other, and which external packages are used."),
        ("graph.html", "Graph (3D)", "An interactive WebGL force-directed dependency graph. Click a node to focus it and unfold its neighbours; colour = folder, size = coupling, dashed edges = heuristic calls."),
        ("types.html", "Types & Members", "Every C# type and method found by syntax-only parsing, grouped by namespace."),
        ("calls.html", "Call Graph", "Method-to-method calls per type (heuristic — matched by name + parameter count)."),
        ("hotspots.html", "Hotspots", "Coupling (fan-in / fan-out), largest files, most-used packages, all TODO/FIXME markers, and the most complex methods with cyclomatic/cognitive scores (hidden by --no-complexity)."),
    ];

    private static readonly (string Term, string Def)[] Glossary =
    [
        ("fan-in", "How many files import this one. High fan-in means changes here ripple widest — risky to touch."),
        ("fan-out", "How many other files this one imports. High fan-out means the file knows about too much."),
        ("ambiguous", "Several declared methods matched a call by name and parameter count, so the exact target is uncertain (shown as a dashed arrow)."),
        ("external", "An import that did not resolve to a file inside this codebase — a package or namespace defined elsewhere."),
        ("heuristic", "Inferred from patterns in the source text, not verified by a compiler. Treat as a strong hint, not a guarantee."),
    ];

    public static string Body(ProjectModel model)
    {
        var sb = new StringBuilder();
        sb.Append("<h1>How to read this site</h1>");
        sb.Append($"""
<p class="lede">This site is a static, offline snapshot of <strong>{Html.Encode(model.RootName)}</strong>, generated by
ArchDiagram from source text alone — no build, no runtime data. Everything below is derived heuristically;
badges marked <span class="badge warn">heuristic</span> mean "inferred from patterns, not guaranteed". Start
with the Overview, then use the sidebar or the sections below to explore.</p>
""");

        // What each page shows.
        sb.Append("<h2>What each page shows</h2>");
        sb.Append("<table class=\"grid\"><thead><tr><th>Page</th><th>What it answers</th></tr></thead><tbody>");
        foreach (var (href, title, what) in PageGuide)
        {
            sb.Append($"<tr><td><a href=\"{href}\">{Html.Encode(title)}</a></td><td>{Html.Encode(what)}</td></tr>");
        }
        sb.Append("</tbody></table>");

        // Reading the diagrams — the legend lives here permanently, expanded.
        sb.Append("<h2>Reading the diagrams</h2>");
        sb.Append("<p class=\"lede\">Every diagram supports scroll-to-zoom, drag-to-pan, <strong>Fit</strong> to reset, "
                + "and export to PNG/SVG or copy as Mermaid. Hover a node for details; click a node to open its page.</p>");
        sb.Append(PageTemplate.Legend(open: true));

        // Limits of the analysis — one honest home for the caveats.
        sb.Append("<h2>How the analysis is derived (and its limits)</h2>");
        sb.Append("""
<div class="note">
<p style="margin:0 0 .5rem">The scan is <strong>static and heuristic</strong> — nothing is compiled or executed:</p>
<ul style="margin:0;padding-left:1.2rem">
  <li>Imports and project references are read from source text (<code>using</code>, <code>import</code>, <code>require</code>, dot-sourcing, <code>.csproj</code>).</li>
  <li>C# types and members come from syntax-only parsing — no symbol resolution, so no generic/overload disambiguation.</li>
  <li>Call links are matched by method name and parameter count; a <em>dashed</em> arrow means several declarations matched (ambiguous).</li>
  <li>Each file's one-line "purpose" is inferred from a head comment, an XML doc summary, or a name convention — hence the <span class="badge warn">heuristic</span> badge.</li>
  <li>Import analysis currently covers C#, TypeScript/JavaScript, Python and PowerShell.</li>
</ul>
<p style="margin:.5rem 0 0">The complete, machine-readable result is in <code>model.json</code> next to this page.</p>
</div>
""");

        // Keyboard & tips.
        sb.Append("<h2>Keyboard &amp; tips</h2>");
        sb.Append("""
<div class="panel"><ul class="member-list" style="font-family:inherit;font-size:.9rem">
  <li style="border-top:none"><kbd>Ctrl</kbd> <kbd>K</kbd> or <kbd>/</kbd> — open search over files, types and methods.</li>
  <li><kbd>↑</kbd> <kbd>↓</kbd> navigate results · <kbd>Enter</kbd> open · <kbd>Esc</kbd> close.</li>
  <li><strong>◐ Theme</strong> (bottom of the sidebar) toggles light / dark; diagrams re-render to match.</li>
  <li>Click a diagram node to open its file page · drag to pan · scroll to zoom · <strong>Fit</strong> to reset the view.</li>
  <li>On Structure and Types, use the filter box to narrow long lists as you type.</li>
</ul></div>
""");

        // Glossary.
        sb.Append("<h2>Glossary</h2>");
        sb.Append("<div class=\"panel\"><ul class=\"member-list\" style=\"font-family:inherit;font-size:.9rem\">");
        var firstTerm = true;
        foreach (var (term, def) in Glossary)
        {
            var style = firstTerm ? " style=\"border-top:none\"" : "";
            firstTerm = false;
            sb.Append($"<li{style}><span class=\"badge accent\">{Html.Encode(term)}</span> {Html.Encode(def)}</li>");
        }
        sb.Append("</ul></div>");

        return sb.ToString();
    }
}
