using System.Text;
using ArchDiagram.Graph;
using ArchDiagram.Rendering;

namespace ArchDiagram.Site.Pages;

public static class IndexPage
{
    // Deterministic language colors for the breakdown bar (fallback cycles).
    private static readonly Dictionary<string, string> LangColors = new(StringComparer.Ordinal)
    {
        ["C#"] = "#2f6fab", ["TypeScript/JavaScript"] = "#e8b73a", ["Python"] = "#3572A5",
        ["PowerShell"] = "#6b46c1", ["SQL"] = "#c0392b", ["HTML"] = "#e34c26", ["CSS"] = "#563d7c",
        ["JSON"] = "#8a8a8a", ["YAML"] = "#6fbf73", ["XML"] = "#0060ac", ["Markdown"] = "#4a4a4a",
        ["MSBuild"] = "#68217a", ["Razor"] = "#512bd4", ["Protobuf"] = "#4d7e65",
    };
    private static readonly string[] FallbackColors = ["#1f8a8a", "#b7791f", "#7a5195", "#ef5675", "#488f31"];

    public static string Body(ProjectModel model, int maxNodes, string generatedOn)
    {
        var totalLoc = model.LanguageLoc.Values.Sum();
        var typeCount = model.Files.Sum(f => f.Types.Count);
        var methodCount = model.Files.Sum(f => f.Types.Sum(t => t.Methods.Count));

        var sb = new StringBuilder();
        sb.Append($"<h1>{Html.Encode(model.RootName)} — Architecture Overview</h1>");
        sb.Append($"""
<p class="lede">This site was generated by <strong>ArchDiagram</strong> from a static scan of
<code>{Html.Encode(model.SourcePath)}</code> on {Html.Encode(generatedOn)}. Start here for the big picture, then drill
down via the sidebar: folder structure, file-to-file dependencies, C# types and members, method call
graphs, and a dedicated page per file. Every diagram supports pan, zoom, hover details, and PNG download.</p>
""");
        sb.Append("<p class=\"note\">New to this report? <a href=\"guide.html\">Read the Guide</a> for how to read each page, "
                + "what the diagram shapes mean, and the limits of the analysis.</p>");

        // Stat tiles.
        sb.Append("<div class=\"tiles\">");
        Tile(sb, model.Files.Count.ToString("N0"), "Files", "structure.html");
        Tile(sb, totalLoc.ToString("N0"), "Lines of code", "structure.html");
        Tile(sb, model.Projects.Count.ToString("N0"), "Projects (.csproj)");
        Tile(sb, typeCount.ToString("N0"), "Types", "types.html");
        Tile(sb, methodCount.ToString("N0"), "Methods", "calls.html");
        Tile(sb, model.FileDependencies.Count(d => d.ToSlug.Length > 0).ToString("N0"), "File links", "dependencies.html");
        Tile(sb, model.Databases.Count.ToString("N0"), "Databases", "dependencies.html");
        Tile(sb, model.LanguageLoc.Count.ToString("N0"), "Languages");
        sb.Append("</div>");

        // Language breakdown bar.
        if (totalLoc > 0)
        {
            sb.Append("<div class=\"panel\"><h2 style=\"margin-top:0\">Language breakdown <span class=\"badge\">by lines of code</span></h2>");
            sb.Append("<div class=\"lang-bar\">");
            var ordered = model.LanguageLoc.OrderByDescending(kv => kv.Value).ThenBy(kv => kv.Key, StringComparer.Ordinal).ToList();
            var fallbackIdx = 0;
            var colors = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var (lang, loc) in ordered)
            {
                var color = LangColors.TryGetValue(lang, out var c) ? c : FallbackColors[fallbackIdx++ % FallbackColors.Length];
                colors[lang] = color;
                var pct = 100.0 * loc / totalLoc;
                sb.Append($"<span style=\"width:{pct:F2}%;background:{color}\" title=\"{Html.Encode(lang)}: {loc:N0} LOC ({pct:F1}%)\"></span>");
            }
            sb.Append("</div><div class=\"lang-legend\">");
            foreach (var (lang, loc) in ordered.Take(10))
            {
                sb.Append($"<span><span class=\"lang-dot\" style=\"background:{colors[lang]}\"></span>{Html.Encode(lang)} · {loc:N0}</span>");
            }
            sb.Append("</div></div>");
        }

        // Architecture. The static Mermaid diagram is genuinely useful when there are
        // multiple projects/folders to relate; when it would collapse to a single node
        // (one project, one top-level folder) the interactive 3D graph is far more
        // informative, so it leads and the static diagram is tucked into a details block.
        var graphHasData = GraphPage.HasData(model);

        var (archLede, archDiagram) = model.Projects.Count > 0
            ? ("Projects discovered in the tree, their project references, and the databases their code connects to. Hover a node for its path, framework and packages.",
               BuildProjectDiagram(model, maxNodes))
            : ("No .NET projects (.csproj) were found, so this overview shows how the top-level folders depend on each other, based on imports between the files inside them.",
               DependenciesPage.BuildFolderOverview(model, maxNodes));

        // The static Mermaid diagram earns its place only when it actually relates several
        // boxes; at ~3 nodes or fewer it collapses to something the interactive graph shows
        // far better, so lead with the graph and tuck the diagram below. Uses the diagram's
        // real node count (deterministic) rather than a project/folder heuristic.
        var trivialArch = archDiagram.TotalNodes <= 3;

        sb.Append("<h2>Architecture</h2>");
        if (trivialArch && graphHasData)
        {
            sb.Append("<p class=\"lede\">The static architecture diagram for this project is only a handful of boxes, "
                    + "so the interactive dependency graph leads here — drag to orbit, scroll to zoom, and click any file to focus it. "
                    + "The static diagram is tucked below.</p>");
            sb.Append(GraphPage.Embed(model, compact: true, relRoot: ""));
            sb.Append("<details class=\"legend\"><summary>Static architecture diagram</summary>");
            sb.Append($"<p class=\"lede\">{archLede}</p>");
            sb.Append(PageTemplate.DiagramBlock("arch", archDiagram, model.RootName + "-architecture"));
            sb.Append(PageTemplate.Legend());
            sb.Append("</details>");
        }
        else
        {
            sb.Append($"<p class=\"lede\">{archLede}</p>");
            sb.Append(PageTemplate.DiagramBlock("arch", archDiagram, model.RootName + "-architecture"));
            sb.Append(PageTemplate.Legend());
            if (graphHasData)
            {
                sb.Append("<h2>Explore in 3D</h2>");
                sb.Append("<p class=\"lede\">The interactive dependency graph plots every file in a WebGL force graph — "
                        + "click a node to focus it and unfold its neighbours, search to jump to a file, or open the "
                        + "<a href=\"graph.html\">full 3D graph</a> for the complete control set.</p>");
                sb.Append(GraphPage.Embed(model, compact: true, relRoot: ""));
            }
        }

        // Diagnostics.
        if (model.Diagnostics.Count > 0)
        {
            sb.Append($"<h2>Scan diagnostics <span class=\"badge warn\">{model.Diagnostics.Count}</span></h2>");
            sb.Append("<div class=\"panel diag-list\"><ul>");
            foreach (var d in model.Diagnostics.Take(50)) { sb.Append($"<li>{Html.Encode(d)}</li>"); }
            if (model.Diagnostics.Count > 50) { sb.Append($"<li>… and {model.Diagnostics.Count - 50} more (see model.json)</li>"); }
            sb.Append("</ul></div>");
        }

        sb.Append("<p class=\"note\">Analysis is static and heuristic: imports and project references are read from source text, " +
                  "C# structure comes from syntax-only parsing (no compilation), and call links are matched by method name and parameter count. " +
                  "The full machine-readable result is in <code>model.json</code> next to this page.</p>");
        return sb.ToString();
    }

    private static void Tile(StringBuilder sb, string num, string label, string? href = null)
    {
        var inner = $"<div class=\"num\">{num}</div><div class=\"lbl\">{Html.Encode(label)}</div>";
        sb.Append(href is null
            ? $"<div class=\"tile\">{inner}</div>"
            : $"<a class=\"tile\" href=\"{href}\">{inner}</a>");
    }

    public static Diagram BuildProjectDiagram(ProjectModel model, int maxNodes)
    {
        var nodes = new List<DiagramNode>();
        var edges = new List<DiagramEdge>();

        foreach (var p in model.Projects)
        {
            var packages = p.PackageReferences.Count == 0 ? "none"
                : string.Join(", ", p.PackageReferences.Take(6)) + (p.PackageReferences.Count > 6 ? ", …" : "");
            var tooltip = $"{p.RelPath}\nTarget: {(p.TargetFramework.Length > 0 ? p.TargetFramework : "unknown")}\nPackages: {packages}";
            nodes.Add(new DiagramNode("proj:" + p.Name, p.Name, "service", Tooltip: tooltip));
        }

        var projNames = new HashSet<string>(model.Projects.Select(p => p.Name), StringComparer.OrdinalIgnoreCase);
        foreach (var p in model.Projects)
        {
            foreach (var r in p.ProjectReferenceNames.Where(projNames.Contains))
            {
                edges.Add(new DiagramEdge("proj:" + p.Name, "proj:" + r, "reference"));
            }
        }

        foreach (var db in model.Databases)
        {
            var tooltip = $"Database node (deduplicated by normalized connection string)\nServer: {(db.Server.Length > 0 ? db.Server : "unknown")}\nCatalog: {(db.Catalog.Length > 0 ? db.Catalog : "unknown")}\nHash: {db.Hash[..16]}…";
            nodes.Add(new DiagramNode("db:" + db.Hash, db.Label, "database", NodeShape.Database, tooltip));
        }
        foreach (var p in model.Projects)
        {
            foreach (var hash in p.ConnectionStrings.Select(c => c.Hash).Distinct())
            {
                edges.Add(new DiagramEdge("proj:" + p.Name, "db:" + hash, "sql"));
            }
        }

        var (n, e) = GraphReducer.TrimToMax(nodes, edges.DistinctBy(x => (x.FromId, x.ToId, x.Label)).ToList(), maxNodes);
        return MermaidRenderer.Render(n, e, totalNodes: nodes.Count);
    }
}
