using System.Text;
using ArchDiagram.Graph;
using ArchDiagram.Rendering;

namespace ArchDiagram.Site.Pages;

public static class IndexPage
{
    public static string Body(ProjectModel model, int maxNodes, string generatedOn)
    {
        // Headline figures describe first-party code (exclude tests and vendored/minified
        // bundles) so they never mischaracterize the project; the excluded totals are shown
        // as an explicit breakdown beneath the language bar.
        var languageLoc = Analysis.CodebaseStats.FirstPartyLanguageLoc(model);
        var totalLoc = languageLoc.Values.Sum();
        var testLoc = Analysis.CodebaseStats.TestLoc(model);
        var vendoredLoc = Analysis.CodebaseStats.VendoredLoc(model);
        var firstParty = model.Files.Where(Analysis.CodebaseStats.IsFirstParty).ToList();
        var typeCount = firstParty.Sum(f => f.Types.Count);
        var methodCount = firstParty.Sum(f => f.Types.Sum(t => t.Methods.Count));

        var sb = new StringBuilder();
        sb.Append($"<h1>{Html.Encode(model.RootName)} — Architecture Overview</h1>");
        if (model.Description.Length > 0)
        {
            sb.Append($"<div class=\"panel\"><strong>About this project</strong> <span class=\"badge accent\">authored</span>"
                    + $"<p style=\"margin:.4rem 0 0\">{Html.Encode(model.Description)}</p></div>");
        }
        sb.Append($"<p class=\"lede\">{Html.Encode(Analysis.NarrativeBuilder.ProjectSummary(model))}</p>");
        sb.Append($"""
<p class="lede">This site was generated by <strong>ArchDiagram</strong> from a static scan of
<code>{Html.Encode(model.SourcePath)}</code> on {Html.Encode(generatedOn)}. Start here for the big picture, then drill
down via the sidebar: folder structure, file-to-file dependencies, C# types and members, method call
graphs, and a dedicated page per file. Every diagram supports pan, zoom, hover details, and PNG download.</p>
""");
        sb.Append("<p class=\"note\">New to this report? <a href=\"guide.html\">Read the Guide</a> for how to read each page, "
                + "what the diagram shapes mean, and the limits of the analysis.</p>");

        AppendDataQuality(sb, model);

        // Stat tiles.
        sb.Append("<div class=\"tiles\">");
        Tile(sb, model.Files.Count.ToString("N0"), "Files", "structure.html");
        Tile(sb, totalLoc.ToString("N0"), "Lines of code (first-party)", "structure.html");
        Tile(sb, model.Projects.Count.ToString("N0"), "Projects (.csproj)");
        Tile(sb, typeCount.ToString("N0"), "Types", "types.html");
        Tile(sb, methodCount.ToString("N0"), "Methods", "calls.html");
        Tile(sb, model.FileDependencies.Count(d => d.ToSlug.Length > 0).ToString("N0"), "File links", "dependencies.html");
        Tile(sb, model.Databases.Count.ToString("N0"), "Databases", "dependencies.html");
        Tile(sb, languageLoc.Count.ToString("N0"), "Languages");
        sb.Append("</div>");

        AppendHealthSummary(sb, model);

        // Language breakdown bar.
        if (totalLoc > 0)
        {
            sb.Append("<div class=\"panel\"><h2 style=\"margin-top:0\">Language breakdown <span class=\"badge\">first-party lines of code</span></h2>");
            sb.Append("<div class=\"lang-bar\">");
            var ordered = languageLoc.OrderByDescending(kv => kv.Value).ThenBy(kv => kv.Key, StringComparer.Ordinal).ToList();
            var fallbackIdx = 0;
            var colors = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var (lang, loc) in ordered)
            {
                var color = LanguagePalette.ColorFor(lang, ref fallbackIdx);
                colors[lang] = color;
                var pct = 100.0 * loc / totalLoc;
                sb.Append($"<span style=\"width:{pct:F2}%;background:{color}\" title=\"{Html.Encode(lang)}: {loc:N0} LOC ({pct:F1}%)\"></span>");
            }
            sb.Append("</div><div class=\"lang-legend\">");
            foreach (var (lang, loc) in ordered.Take(10))
            {
                sb.Append($"<span><span class=\"lang-dot\" style=\"background:{colors[lang]}\"></span>{Html.Encode(lang)} · {loc:N0}</span>");
            }
            sb.Append("</div>");
            if (testLoc > 0 || vendoredLoc > 0)
            {
                var parts = new List<string> { $"<strong>{totalLoc:N0}</strong> first-party" };
                if (testLoc > 0) { parts.Add($"{testLoc:N0} test"); }
                if (vendoredLoc > 0) { parts.Add($"{vendoredLoc:N0} vendored/minified"); }
                sb.Append($"<p class=\"note\" style=\"margin:.6rem 0 0\">Lines of code: {string.Join(" · ", parts)}. "
                        + "Headline figures above count first-party code only, so bundled libraries and tests don't skew them.</p>");
            }
            sb.Append("</div>");
        }

        // Architecture. The static Mermaid diagram is genuinely useful when there are
        // multiple projects/folders to relate; when it would collapse to a single node
        // (one project, one top-level folder) the interactive 3D graph is far more
        // informative, so it leads and the static diagram is tucked into a details block.
        var graphHasData = GraphPage.HasData(model);

        var (archLede, archDiagram) = model.Projects.Count > 0
            ? ("Projects discovered in the tree, their project references, and the databases their code connects to. Hover a node for its path, framework and packages.",
               BuildProjectDiagram(model, maxNodes))
            : ("No .NET projects (.csproj) were found, so this overview shows how the top-level folders depend on each other, based on imports between the files inside them.",
               DependenciesPage.BuildFolderOverview(model, maxNodes));

        // The static Mermaid diagram earns its place only when it actually relates several
        // boxes; at ~3 nodes or fewer it collapses to something the interactive graph shows
        // far better, so lead with the graph and tuck the diagram below. Uses the diagram's
        // real node count (deterministic) rather than a project/folder heuristic.
        var trivialArch = archDiagram.TotalNodes <= 3;

        sb.Append("<h2>Architecture</h2>");
        if (trivialArch && graphHasData)
        {
            sb.Append("<p class=\"lede\">The static architecture diagram for this project is only a handful of boxes, "
                    + "so the interactive dependency graph leads here — drag to orbit, scroll to zoom, and click any file to focus it. "
                    + "The static diagram is tucked below.</p>");
            sb.Append(GraphPage.Embed(model, compact: true, relRoot: ""));
            sb.Append("<details class=\"legend\"><summary>Static architecture diagram</summary>");
            sb.Append($"<p class=\"lede\">{archLede}</p>");
            sb.Append(PageTemplate.DiagramBlock("arch", archDiagram, model.RootName + "-architecture"));
            sb.Append(PageTemplate.Legend());
            sb.Append("</details>");
        }
        else
        {
            sb.Append($"<p class=\"lede\">{archLede}</p>");
            sb.Append(PageTemplate.DiagramBlock("arch", archDiagram, model.RootName + "-architecture"));
            sb.Append(PageTemplate.Legend());
            if (graphHasData)
            {
                sb.Append("<h2>Explore in 3D</h2>");
                sb.Append("<p class=\"lede\">The interactive dependency graph plots every file in a WebGL force graph — "
                        + "click a node to focus it and unfold its neighbours, search to jump to a file, or open the "
                        + "<a href=\"graph.html\">full 3D graph</a> for the complete control set.</p>");
                sb.Append(GraphPage.Embed(model, compact: true, relRoot: ""));
            }
        }

        // "Start here": the most central files for a newcomer to read first. Placed below the
        // architecture diagrams so the big picture leads and the reading list follows.
        AppendStartHere(sb, model);

        // Diagnostics.
        if (model.Diagnostics.Count > 0)
        {
            sb.Append($"<h2 id=\"diagnostics\">Scan diagnostics <span class=\"badge warn\">{model.Diagnostics.Count}</span></h2>");
            sb.Append("<div class=\"panel diag-list\"><ul>");
            foreach (var d in model.Diagnostics.Take(50)) { sb.Append($"<li>{Html.Encode(d)}</li>"); }
            if (model.Diagnostics.Count > 50) { sb.Append($"<li>… and {model.Diagnostics.Count - 50} more (see model.json)</li>"); }
            sb.Append("</ul></div>");
        }

        sb.Append("<p class=\"note\">Analysis is static and heuristic: imports and project references are read from source text, " +
                  "C# structure comes from syntax-only parsing (no compilation), and call links are matched by method name and parameter count. " +
                  "The full machine-readable result is in <code>model.json</code> next to this page.</p>");
        return sb.ToString();
    }

    /// <summary>Ranks the most central files (fan-in, calls, entry points, size) so a
    /// newcomer knows where to start reading. Empty-state when nothing scores.</summary>
    private static void AppendStartHere(StringBuilder sb, ProjectModel model)
    {
        var ranked = Analysis.ImportanceScorer.Rank(model, 12);
        sb.Append("<h2>Start here <span class=\"badge accent\">most central files</span></h2>");
        if (ranked.Count == 0)
        {
            sb.Append("<div class=\"panel empty-state\"><div class=\"big\">◈</div>" +
                      "<p>No dependency or call links were detected, so there is nothing to rank yet. " +
                      "Browse the <a href=\"structure.html\">Structure</a> page to explore the files.</p></div>");
            return;
        }
        sb.Append("<p class=\"lede\">If you are new to this codebase, read these first. They are ranked by how "
                + "much the rest of the code depends on them (fan-in), how often they are called, whether they "
                + "are an entry point, and their size. Ranking is heuristic — a strong hint, not a guarantee.</p>");
        sb.Append("<table class=\"grid\"><thead><tr><th>#</th><th>File</th><th>Why it matters</th><th>Purpose</th></tr></thead><tbody>");
        var rank = 0;
        foreach (var s in ranked)
        {
            rank++;
            sb.Append($"<tr><td>{rank}</td><td><a href=\"files/{s.File.Slug}.html\">{Html.Encode(s.File.RelPath)}</a></td>" +
                      $"<td><span class=\"badge\">{Html.Encode(s.Reason)}</span></td>" +
                      $"<td>{Html.Encode(s.File.Purpose)}</td></tr>");
        }
        sb.Append("</tbody></table>");
    }

    /// <summary>A short "how much to trust this" panel: what the scan measures exactly vs
    /// heuristically, and a pointer to any scan diagnostics. Sets reviewer expectations up
    /// front so a heuristic figure is never mistaken for ground truth.</summary>
    private static void AppendDataQuality(StringBuilder sb, ProjectModel model)
    {
        var csharpFiles = model.Files.Count(f => f.Language == "C#" && !f.IsTest);
        var items = new List<string>
        {
            "<strong>Exact:</strong> file inventory, sizes, folder structure, and project references (read from <code>.csproj</code>).",
            "<strong>Syntax-only:</strong> C# types and members come from parsing without compiling — generics, partials and generated code may be approximate.",
            "<strong>Heuristic:</strong> import/dependency links are matched from source text; call links are matched by method name and parameter count, so overloads across types can over- or under-link.",
            "<strong>Excluded from headline figures:</strong> test files and vendored/minified bundles (shown separately), so size and language reflect first-party code.",
        };
        if (csharpFiles == 0)
        {
            items.Add("<strong>Note:</strong> no C# detected — Types, Members and Call Graph pages will be sparse; this codebase is analysed at inventory/import level only.");
        }
        var diag = model.Diagnostics.Count > 0
            ? $" <a href=\"#diagnostics\">{model.Diagnostics.Count} scan diagnostic(s)</a> were recorded (e.g. files too large for deep analysis, unreadable paths)."
            : " No scan diagnostics were recorded.";
        sb.Append("<details class=\"legend\"><summary>Data quality &amp; confidence — what these numbers mean</summary>");
        sb.Append("<div class=\"legend-grid\" style=\"flex-direction:column;gap:.4rem\">");
        foreach (var it in items) { sb.Append($"<span class=\"legend-item\">{it}</span>"); }
        sb.Append($"<span class=\"legend-item\">{diag}</span>");
        sb.Append("</div></details>");
    }

    /// <summary>Dashboard "health at a glance": the scorecard's overall grade and the signals
    /// that need attention, each a link to the page that explains and fixes it. Turns the
    /// Overview into a landing that answers "is this healthy, and where do I look?".</summary>
    private static void AppendHealthSummary(StringBuilder sb, ProjectModel model)
    {
        var card = Analysis.ScorecardBuilder.Build(model);
        var (label, cls) = card.Overall switch
        {
            Analysis.ScorecardBuilder.Status.Ok => ("PASS", "ok"),
            Analysis.ScorecardBuilder.Status.Watch => ("WATCH", "warn"),
            Analysis.ScorecardBuilder.Status.Fail => ("AT RISK", "danger"),
            _ => ("—", "border"),
        };
        var attention = card.Rows
            .Where(r => r.Status is Analysis.ScorecardBuilder.Status.Watch or Analysis.ScorecardBuilder.Status.Fail)
            .ToList();

        sb.Append($"<div class=\"panel\" style=\"border-color:var(--{cls})\">");
        sb.Append($"<h2 style=\"margin-top:0\">Health at a glance <span class=\"badge {(cls == "ok" ? "ok" : "warn")}\">{label}</span> "
                + "<a href=\"scorecard.html\" style=\"font-size:.8rem;font-weight:400\">full scorecard →</a></h2>");
        if (attention.Count == 0)
        {
            sb.Append("<p class=\"note\" style=\"margin:0\">All measured signals pass. See the scorecard for detail.</p>");
        }
        else
        {
            sb.Append("<p class=\"lede\" style=\"margin:.2rem 0 .6rem\">Signals needing attention (each links to the page that explains and fixes it):</p>");
            sb.Append("<div class=\"lang-legend\" style=\"gap:.5rem\">");
            foreach (var r in attention)
            {
                var rc = r.Status == Analysis.ScorecardBuilder.Status.Fail ? "warn" : "";
                var link = r.Link.Length > 0 ? r.Link : "scorecard.html";
                sb.Append($"<a class=\"badge {rc}\" href=\"{Html.Encode(link)}\" style=\"text-decoration:none\">"
                        + $"{Html.Encode(r.Metric)}: {Html.Encode(r.Value)}</a>");
            }
            sb.Append("</div>");
        }
        sb.Append("</div>");
    }

    private static void Tile(StringBuilder sb, string num, string label, string? href = null)
    {
        var inner = $"<div class=\"num\">{num}</div><div class=\"lbl\">{Html.Encode(label)}</div>";
        sb.Append(href is null
            ? $"<div class=\"tile\">{inner}</div>"
            : $"<a class=\"tile\" href=\"{href}\">{inner}</a>");
    }

    public static Diagram BuildProjectDiagram(ProjectModel model, int maxNodes)
    {
        var nodes = new List<DiagramNode>();
        var edges = new List<DiagramEdge>();

        foreach (var p in model.Projects)
        {
            var packages = p.PackageReferences.Count == 0 ? "none"
                : string.Join(", ", p.PackageReferences.Take(6)) + (p.PackageReferences.Count > 6 ? ", …" : "");
            var tooltip = $"{p.RelPath}\nTarget: {(p.TargetFramework.Length > 0 ? p.TargetFramework : "unknown")}\nPackages: {packages}";
            nodes.Add(new DiagramNode("proj:" + p.Name, p.Name, "service", Tooltip: tooltip));
        }

        var projNames = new HashSet<string>(model.Projects.Select(p => p.Name), StringComparer.OrdinalIgnoreCase);
        foreach (var p in model.Projects)
        {
            foreach (var r in p.ProjectReferenceNames.Where(projNames.Contains))
            {
                edges.Add(new DiagramEdge("proj:" + p.Name, "proj:" + r, "reference"));
            }
        }

        foreach (var db in model.Databases)
        {
            var tooltip = $"Database node (deduplicated by normalized connection string)\nServer: {(db.Server.Length > 0 ? db.Server : "unknown")}\nCatalog: {(db.Catalog.Length > 0 ? db.Catalog : "unknown")}\nHash: {db.Hash[..16]}…";
            nodes.Add(new DiagramNode("db:" + db.Hash, db.Label, "database", NodeShape.Database, tooltip));
        }
        foreach (var p in model.Projects)
        {
            foreach (var hash in p.ConnectionStrings.Select(c => c.Hash).Distinct())
            {
                edges.Add(new DiagramEdge("proj:" + p.Name, "db:" + hash, "sql"));
            }
        }

        var (n, e) = GraphReducer.TrimToMax(nodes, edges.DistinctBy(x => (x.FromId, x.ToId, x.Label)).ToList(), maxNodes);
        return MermaidRenderer.Render(n, e, totalNodes: nodes.Count);
    }
}
